// <auto-generated />
using System;
using MediTrack.FollowUpService.API.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediTrack.FollowUpService.API.Migrations
{
    [DbContext(typeof(FollowUpDbContext))]
    [Migration("20260710160534_AddIdempotencyRecords")]
    partial class AddIdempotencyRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MediTrack.FollowUpService.API.Domain.Model.Aggregates.AppointmentCompliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int")
                        .HasColumnName("appointment_id");

                    b.Property<bool>("Attended")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("attended");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext")
                        .HasColumnName("notes");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.ToTable("appointment_compliances", (string)null);
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Domain.Model.Aggregates.AppointmentReference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("scheduled_at");

                    b.HasKey("Id");

                    b.ToTable("appointment_reference", (string)null);
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Domain.Model.Aggregates.Medication", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("dose");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<int>("FrequencyHours")
                        .HasColumnType("int")
                        .HasColumnName("frequency_hour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<int>("StockAlertThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_alert_threshold");

                    b.Property<int>("StockCount")
                        .HasColumnType("int")
                        .HasColumnName("stock_count");

                    b.HasKey("Id");

                    b.ToTable("medications", (string)null);
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Domain.Model.Aggregates.MedicationCompliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("DoseScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("dose_schedule_id");

                    b.Property<DateTime?>("OfflineRecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("offline_recorded_at");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<bool>("Synced")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("synced");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("DoseScheduleId");

                    b.ToTable("medication_compliances", (string)null);
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Domain.Model.Aggregates.OfflineSyncQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("entity_type");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("payload");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("queued_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("synced_at");

                    b.HasKey("Id");

                    b.ToTable("offline_sync_queue", (string)null);
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Domain.Models.DoseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MedicationId")
                        .HasColumnType("int")
                        .HasColumnName("medication_id");

                    b.Property<TimeSpan>("ScheduledTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("scheduled_time");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.ToTable("dose_schedules", (string)null);
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Infrastructure.Persistence.EFC.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Infrastructure.Persistence.EFC.OutboxMessage", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Infrastructure.Persistence.EFC.ProcessedEvent", b =>
                {
                    b.Property<byte[]>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("EventId");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Domain.Model.Aggregates.MedicationCompliance", b =>
                {
                    b.HasOne("MediTrack.FollowUpService.API.Domain.Models.DoseSchedule", "DoseSchedule")
                        .WithMany()
                        .HasForeignKey("DoseScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoseSchedule");
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Domain.Models.DoseSchedule", b =>
                {
                    b.HasOne("MediTrack.FollowUpService.API.Domain.Model.Aggregates.Medication", "Medication")
                        .WithMany("Schedules")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("MediTrack.FollowUpService.API.Domain.Model.Aggregates.Medication", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
